# Generated by Django 5.0.2 on 2024-03-23 09:38

import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('rasm', models.ImageField(upload_to='rasm/images')),
                ('text', models.TextField()),
                ('chopetilish_vaqti', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-chopetilish_vaqti'],
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
