# Generated by Django 5.0.2 on 2024-06-26 12:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_af',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_ar',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_ar_dz',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_ast',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_az',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_be',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_bg',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_bn',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_br',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_bs',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_ca',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_ckb',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_cs',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_cy',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_da',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_de',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_dsb',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_el',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_en',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_en_au',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_en_gb',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_eo',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_es',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_es_ar',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_es_co',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_es_mx',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_es_ni',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_es_ve',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_et',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_eu',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_fa',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_fi',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_fr',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_fy',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_ga',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_gd',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_gl',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_he',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_hi',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_hr',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_hsb',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_hu',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_hy',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_ia',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_ig',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_ind',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_io',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_is',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_it',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_ja',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_ka',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_kab',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_kk',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_km',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_kn',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_ko',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_ky',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_lb',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_lt',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_lv',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_mk',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_ml',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_mn',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_mr',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_ms',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_my',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_nb',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_ne',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_nl',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_nn',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_os',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_pa',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_pl',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_pt',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_pt_br',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_ro',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_ru',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_sk',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_sl',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_sq',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_sr',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_sr_latn',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_sv',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_sw',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_ta',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_te',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_tg',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_th',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_tk',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_tr',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_tt',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_udm',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_ug',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_uk',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_ur',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_uz',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_vi',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_zh_hans',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='chopetilish_vaqti_zh_hant',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_af',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_ar_dz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_ast',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_be',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_bg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_bn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_br',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_bs',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_ca',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_ckb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_cs',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_cy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_da',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_dsb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_el',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_en_au',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_en_gb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_eo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_es_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_es_co',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_es_mx',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_es_ni',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_es_ve',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_et',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_eu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_fa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_fi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_fy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_ga',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_gd',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_gl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_he',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_hi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_hr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_hsb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_hu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_hy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_ia',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_ig',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_ind',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_io',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_is',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_it',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_ja',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_ka',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_kab',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_kk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_km',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_kn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_ko',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_ky',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_lb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_lt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_lv',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_mk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_ml',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_mn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_mr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_ms',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_my',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_nb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_ne',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_nl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_nn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_os',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_pa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_pl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_pt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_pt_br',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_ro',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_sk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_sl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_sq',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_sr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_sr_latn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_sv',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_sw',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_ta',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_te',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_tg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_th',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_tk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_tt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_udm',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_ug',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_uk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_ur',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_vi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_zh_hans',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='nomi_zh_hant',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_af',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_ar_dz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_ast',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_be',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_bg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_bn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_br',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_bs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_ca',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_ckb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_cs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_cy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_da',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_dsb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_el',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_en_au',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_en_gb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_eo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_es_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_es_co',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_es_mx',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_es_ni',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_es_ve',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_et',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_eu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_fa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_fi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_fy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_ga',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_gd',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_gl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_he',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_hi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_hr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_hsb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_hu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_hy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_ia',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_ig',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_ind',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_io',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_is',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_ja',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_ka',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_kab',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_kk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_km',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_kn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_lb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_lt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_lv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_mk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_ml',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_mn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_mr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_ms',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_my',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_nb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_ne',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_nn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_os',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_pa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_pt_br',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_ro',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_sk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_sl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_sq',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_sr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_sr_latn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_sv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_sw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_ta',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_te',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_tg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_th',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_tk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_tt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_udm',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_ug',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_ur',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_vi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_zh_hans',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='matn',
            name='text_zh_hant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_af',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_ar_dz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_ast',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_be',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_bg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_bn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_br',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_bs',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_ca',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_ckb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_cs',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_cy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_da',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_dsb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_el',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_en_au',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_en_gb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_eo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_es_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_es_co',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_es_mx',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_es_ni',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_es_ve',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_et',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_eu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_fa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_fi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_fy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_ga',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_gd',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_gl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_he',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_hi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_hr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_hsb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_hu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_hy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_ia',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_ig',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_ind',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_io',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_is',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_it',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_ja',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_ka',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_kab',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_kk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_km',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_kn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_ko',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_ky',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_lb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_lt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_lv',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_mk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_ml',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_mn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_mr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_ms',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_my',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_nb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_ne',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_nl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_nn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_os',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_pa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_pl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_pt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_pt_br',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_ro',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_sk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_sl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_sq',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_sr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_sr_latn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_sv',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_sw',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_ta',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_te',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_tg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_th',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_tk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_tt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_udm',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_ug',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_uk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_ur',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_vi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_zh_hans',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rasmlar',
            name='nomi_zh_hant',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
